# Generated by Django 4.1.5 on 2023-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_biding'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='biding',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
