# Generated by Django 4.1.5 on 2023-02-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_biding_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biding',
            options={},
        ),
    ]
