# Generated by Django 4.1.5 on 2023-02-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='isActive',
            new_name='active',
        ),
    ]
