# Generated by Django 4.1.5 on 2023-02-03 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_text_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
